
name:  test qt action release

on:
  push:
    branches: "main"

jobs:
  job:
    name: ${{ github.workflow }}
    runs-on: windows-2022
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
          
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.4.2'
          host: 'windows'
          target: 'desktop'
          set-env: 'true'
          modules: 'qtdatavis3d'


      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 3.24.3
          ninjaVersion:  1.11.1


      - name: Configuration
        run: |
          cmake . -B build 
          cd build
          cmake --build . --config Release
          
      - name: CTest
        run: |
          cd build
          ctest --verbose -C Release -T test --output-on-failure
