name:  test_qt

on:
  push:
    branches: "test_qt"

jobs:
  job:
    name: ${{ github.workflow }}
    runs-on: windows-latest
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
      - uses: TheMrMilchmann/setup-msvc-dev@v2
        with:
          arch: x64
       
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.4.2'
          host: 'windows'
          target: 'desktop'
          set-env: 'true'

      - name: Configure  project on windows
        run: |
              qmake
              nmake
              
      - name: windeployqt 
        run: |
          cd release
          windeployqt.exe  main.exe  
      
        

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-qt
          path: ./release
