name:  test_qt

on:
  push:
    branches: "main"

jobs:
  job:
    name: ${{ github.workflow }}
    runs-on: windows-latest
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
       
      - name: Add msbuild to PATH
        uses: seanmiddleditch/gha-setup-vsdevenv@master
     
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.4.2'
          host: 'windows'
          target: 'desktop'
          set-env: 'true'
          modules: 'qtdatavis3d'

      - name: Configure  project on windows
        run: |
            qmake
            nmake
              
      - name: windeployqt 
        run: |
              mkdir target
              copy ./release/rotations.exe  ./target 
              cd target
              windeployqt  rotations.exe  

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-qt
          path: ./target
