name:  test qt action release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+.[0-9]+

jobs:
  job1:
    name: ${{ github.workflow }}
    runs-on: windows-2022
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
          
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.4.2'
          host: 'windows'
          target: 'desktop'
          set-env: 'true'
          modules: 'qtdatavis3d'

      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 3.24.3
          ninjaVersion:  1.11.1


      - name: Configuration
        run: |
          cmake . -B build 
          cd build
          cmake --build . --config Release

      - name: CTest
        run: |
          cd build
          ctest --verbose -C Release -T test --output-on-failure

      - name: windeployqt 
        run: |
          mkdir target
          copy .\build\Release\rotations.exe .\target
          cd target
          windeployqt.exe  rotations.exe  
          
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rotations
          path: ./target
    
          
      - name: 7z
        uses: DuckSoft/create-7z-action@v1.0
        with:
          pathSource: ./target
          pathTarget: rotations.tar

      - name: get note
        shell: python
        run: |
          import os;
          f=open('releasenotes.md',"r");
          obj={i[0].strip():i[1:] for i in [i.split('-') for i in f.read().split('##')[1:]]};
          f.close();
          note=[obj[i] for i in obj if i=='${{github.ref_name}}'];note=[note[0] if note else ''][0];
          file=open('releasenotes.txt','w+');
          tmp=[file.write(n.strip()+'\n') for n in note];
          file.close();
     
      - run: .\releasenotes.ps1

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{github.ref_name}}
          name: ${{github.ref_name}}
          body: ${{env.NOTE}}
          prerelease: false
          draft: false
          files: rotations.tar
